version: '3'

services:
  frontend:
    build: ./frontend/vue-crud-app
    ports:
      - '8080:8080'
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: topza1997
      DB_NAME: crud_db

  db:
    image: postgres
    environment:
      POSTGRES_DB: crud_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: topza1997
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
